apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-dentro-container
          name: primeiro-volume
  volumes:
    - name: primeiro-volume
      hostPath:
        path: /C/Users/Lenovo/Desktop/primeiro-volume
        type: Directory
